### PR TITLE
Using TimeSeries 0.14.0

### PR DESCRIPTION
**Pull request by femtotrader**
TimeSeries changed its API
See https://github.com/JuliaStats/TimeSeries.jl/releases/tag/v0.14.0

This PR fixes TimeSeriesResampler.jl to stick with this API changes

### CODE REVIEW

**Comment by iblislin** [comment]
(I really want to merge this repo into TimeSeries.jl)

**Comment by femtotrader** [comment]
All the resampling code?

**Comment by femtotrader** [comment]
I'm totally ok but it will add a dependency to https://github.com/femtotrader/TimeFrames.jl
and TimeFrames probably need [more care](https://github.com/femtotrader/TimeFrames.jl/issues).

We are still far from what Pandas have (especially for non regulary spaced TimeFrames https://github.com/femtotrader/TimeFrames.jl/issues/2 )

**Comment by iblislin** [comment]
I'm okay with adding TimeFrames as depedency.
Merging this repo into TimeSeries will be my next big TODO.

**Pull request merged**
